name: nightsky-compile
run-name: nightsky-compilation fired by ${{ github.actor }}
on: [workflow_dispatch]
jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: sparksrs
          path: target/release/sparksrs
