name: vultr-compile
run-name: vultr-compilation fired by ${{ github.actor }}
on: [workflow_dispatch]
jobs:
  compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
